#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["HelloWorld.UnitTests/HelloWorld.UnitTests.csproj", "HelloWorld.UnitTests/"]
COPY ["HelloWorld.BDDTests/HelloWorld.BDDTests.csproj", "HelloWorld.BDDTests/"]
COPY ["run-tests.sh", "."]
#if you are using a private nuget server add it here:
#RUN dotnet nuget add source https://<NUGET_SERVER_DOMAIN>/v3/index.json -n <SERVER_NAME>
RUN dotnet restore "HelloWorld.UnitTests/HelloWorld.UnitTests.csproj"
RUN dotnet restore "HelloWorld.BDDTests/HelloWorld.BDDTests.csproj"
COPY . .
RUN dotnet build "HelloWorld.UnitTests/HelloWorld.UnitTests.csproj" -c Release -o /app/build
RUN dotnet build "HelloWorld.BDDTests/HelloWorld.BDDTests.csproj" -c Release -o /app/build

FROM build AS run-tests
WORKDIR /src
ARG ASPNETCORE_ENVIRONMENT
ENV ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
COPY ./solution.runsettings ./test.runsettings
RUN sed -i "s/Local/$ASPNETCORE_ENVIRONMENT/" ./test.runsettings
ENTRYPOINT ["./run-tests.sh"]

